[use_git]
ignore = []
select = []
warning = []
ignorable_errors = ["RM101"]

[validate_all]
ignore = []
select = ["BA101"]
warning = []
ignorable_errors = []

[yuval_Categories]
ignore = ["RM101, RM102"]
select = []
warning = []
ignorable_errors = []


[support_level]

[support_level.community]
ignore = []

[support_level.partner]
ignore = []

[support_level.xsoar]
ignore = []
